Repository webpack-contrib/url-loader, pull requests merged in 2018-03, with the labels that each got.

#113 fix(index): use `Buffer.from` instead of deprecated `new Buffer`
  src/index.js
Labels: semver: Patch, status: Approved, type: Bug

#114 test: standardize (`@webpack-contrib/test-utils`)
  package-lock.json
  package.json
  test/Errors.test.js
  test/__snapshots__/Errors.test.js.snap
  test/helpers/compiler.js
  test/loader.test.js
  test/options/fallback.test.js
  test/options/limit.test.js
  test/options/mimetype.test.js
Labels: pr_action: Review, priority: 3 (required), semver: Patch, status: Pending, type: Test

#117 docs(README): add missing badges
  README.md
Labels: semver: Patch, status: Approved, type: Documentation

#116 fix(index): revert to CJS exports (`module.exports`)
  src/index.js
  test/__snapshots__/loader.test.js.snap
  test/options/__snapshots__/limit.test.js.snap
  test/options/__snapshots__/mimetype.test.js.snap
Labels: semver: Patch, status: Approved, type: Bug
