Repository webpack-contrib/url-loader, pull requests merged in 2018-08, with the labels that each got.

#136 refactor(package): switch from `@webpack-contrib/schema-utils` to `schema-utils` (`dependencies`)
  package-lock.json
  package.json
  src/index.js
  test/__snapshots__/Errors.test.js.snap
Labels: semver: Patch, status: Approved, type: Refactor

#137 chore(package): use caret range for `schema-utils` (`dependencies`)
  package.json
Labels: semver: Patch, status: Approved, type: Chore

#140 refactor(index): remove unnecessary delete
  src/index.js
Labels: semver: Patch, status: Pending, type: Refactor

#145 fix(utils/normalizeFallback): fallback options behaviour (`options.fallback`)
  src/index.js
  src/utils/normalizeFallback.js
  test/__snapshots__/fallback-option.test.js.snap
  test/__snapshots__/limit-option.test.js.snap
  test/__snapshots__/mimetype-option.test.js.snap
  test/cjs.test.js
  test/fallback-option.test.js
  test/fixtures/x-custom-loader/index.js
  test/limit-option.test.js
  test/mimetype-option.test.js
  test/options/__snapshots__/fallback.test.js.snap
  test/options/__snapshots__/limit.test.js.snap
  test/options/__snapshots__/mimetype.test.js.snap
  test/options/fallback.test.js
  test/options/limit.test.js
  test/options/mimetype.test.js
  test/utils/__snapshots__/normalizeFallback.test.js.snap
  test/utils/normalizeFallback.test.js
Labels: pr_action: Review, semver: Patch, status: Approved, type: Bug
